In [1]:
import pandas as pd
import os
from getpass import getpass

In [7]:
df = pd.read_csv("/content/gas_price_brazil/2004-2021.tsv", sep='\t')

In [8]:
df.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

Initial Inspection and Data Quality

In [9]:
print(df.shape)  # number of line and columns

(120823, 18)

In [10]:
df.info() # Verifying data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  object
 1   DATA FINAL                     120823 non-null  object
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 16.6+ MB

In [11]:
df.isnull().sum() # null values

DATA INICIAL                     0
DATA FINAL                       0
REGIÃO                           0
ESTADO                           0
PRODUTO                          0
NÚMERO DE POSTOS PESQUISADOS     0
UNIDADE DE MEDIDA                0
PREÇO MÉDIO REVENDA              0
DESVIO PADRÃO REVENDA            0
PREÇO MÍNIMO REVENDA             0
PREÇO MÁXIMO REVENDA             0
MARGEM MÉDIA REVENDA             0
COEF DE VARIAÇÃO REVENDA         0
PREÇO MÉDIO DISTRIBUIÇÃO         0
DESVIO PADRÃO DISTRIBUIÇÃO       0
PREÇO MÍNIMO DISTRIBUIÇÃO        0
PREÇO MÁXIMO DISTRIBUIÇÃO        0
COEF DE VARIAÇÃO DISTRIBUIÇÃO    0
dtype: int64

In [12]:
df.duplicated().sum()  # Detect and remove duplicate records.

np.int64(0)

Descriptive Statistical Analysis

In [13]:
df.describe()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,COEF DE VARIAÇÃO REVENDA
count,120823.000000,120823.000000,120823.000000,120823.000000,120823.000000,120823.000000
mean,221.066461,11.473440,0.684132,9.977821,13.233902,0.045298
std,387.940239,19.161823,1.403317,16.433783,22.451445,0.024763
min,1.000000,0.766000,0.000000,0.590000,0.999000,0.000000
25%,39.000000,2.157000,0.075000,1.989000,2.420000,0.029000
50%,99.000000,2.899000,0.121000,2.690000,3.200000,0.041000
75%,226.000000,4.026000,0.204000,3.790000,4.589000,0.058000
max,4167.000000,107.500000,10.748000,100.000000,120.000000,0.395000

##EDA

In [14]:
df['DATA INICIAL']

0         2004-05-09
1         2004-05-09
2         2004-05-09
3         2004-05-09
4         2004-05-09
             ...
120818    2021-04-25
120819    2021-04-25
120820    2021-04-25
120821    2021-04-25
120822    2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: object

In [15]:
df['DATA INICIAL'] = pd.to_datetime(df['DATA INICIAL'])
df['DATA FINAL'] = pd.to_datetime(df['DATA FINAL'])

In [16]:
df['ANO MES'] = df['DATA FINAL'].apply(lambda x : '{}'.format(x.year)) + df['DATA FINAL'].apply(lambda x : '-{:02d}'.format(x.month))

In [17]:
df['ANO MES']

0         2004-05
1         2004-05
2         2004-05
3         2004-05
4         2004-05
           ...
120818    2021-05
120819    2021-05
120820    2021-05
120821    2021-05
120822    2021-05
Name: ANO MES, Length: 120823, dtype: object

In [18]:
df.columns

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO',
       'ANO MES'],
      dtype='object')

# filtering the dataframe only with the GASOLINA COMUM registers

In [19]:
df['PRODUTO'].value_counts()

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

In [21]:
df2 = df[df['PRODUTO'] == "GASOLINA COMUM"]

In [22]:
df2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO MES
12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.990,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004-05
12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.850,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004-05
12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.000,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004-05
12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.970,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004-05
12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.000,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,5.310,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,4.640,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05

# Average gasoline price in August 2008

In [23]:
df2[df['ANO MES'] == '2008-09']['PREÇO MÉDIO REVENDA'].mean()

<ipython-input-23-7d5cb09bd601>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2[df['ANO MES'] == '2008-09']['PREÇO MÉDIO REVENDA'].mean()

np.float64(2.611009259259259)

# Average gasoline price in August 2008 in Sao Paulo

estrutura de colchetes

> [selection] [[list of columns or only one list]]

In [24]:
df2[(df2['ANO MES'] == '2008-09') & (df2['ESTADO'] == 'SAO PAULO')]['PREÇO MÉDIO REVENDA'].mean()

np.float64(2.40325)

#When did the gas price go up to 5 dollars, and in which state did that happen?

In [25]:
df2[df2['PREÇO MÁXIMO REVENDA'] > 5][['ANO MES', 'ESTADO', 'PREÇO MÉDIO REVENDA']]

        ANO MES          ESTADO  PREÇO MÉDIO REVENDA
92471   2017-09            ACRE                4.373
92771   2017-09            ACRE                4.496
93072   2017-09            ACRE                4.516
93371   2017-10            ACRE                4.521
93671   2017-10            ACRE                4.524
...         ...             ...                  ...
120721  2021-05         RORAIMA                5.364
120722  2021-05  SANTA CATARINA                5.051
120723  2021-05       SAO PAULO                5.265
120724  2021-05         SERGIPE                5.586
120725  2021-05       TOCANTINS                5.751

[1599 rows x 3 columns]

#Average gas price at the south states in 2012

In [26]:
df_south = df2[(df2['REGIÃO'] == 'SUL')]

In [27]:
df_south[df_south['DATA INICIAL'].apply(lambda x: x.year) == 2012]['PREÇO MÁXIMO REVENDA'].mean()

np.float64(3.0785723270440246)

##Year-over-year percentage change in gasoline prices in the state of Rio de Janeiro

In [28]:
df_rio = df2[df2['ESTADO'] == 'RIO DE JANEIRO']

In [29]:
df_rio['ANO'] = df_rio['DATA INICIAL'].apply(lambda x: '{}'.format(x.year))

<ipython-input-29-f9ebd2d929bf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rio['ANO'] = df_rio['DATA INICIAL'].apply(lambda x: '{}'.format(x.year))

In [30]:
df_rio.groupby('ANO')['PREÇO MÉDIO REVENDA'].mean()

ANO
2004    2.175500
2005    2.339500
2006    2.560679
2007    2.532288
2008    2.547308
2009    2.566120
2010    2.648673
2011    2.835846
2012    2.853698
2013    2.998885
2014    3.134635
2015    3.549882
2016    3.919192
2017    4.112774
2018    4.858058
2019    4.858173
2020    4.761205
2021    5.625294
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [ ]:
(df_rio_perct / df_rio_perct.shift(1) -1)*100

In [ ]:
dfrio

### Time series with absolute and percentage differences between the lowest and highest prices, separated by state.

In [41]:
df_max = df2.groupby('ANO MES').max()['PREÇO MÉDIO REVENDA']

In [42]:
df_min = df2.groupby('ANO MES').min()['PREÇO MÉDIO REVENDA']

In [43]:
df_max

ANO MES
2004-05    2.438
2004-06    2.496
2004-07    2.545
2004-08    2.560
2004-09    2.570
           ...
2021-01    5.213
2021-02    5.809
2021-03    6.688
2021-04    6.227
2021-05    6.258
Name: PREÇO MÉDIO REVENDA, Length: 204, dtype: float64

In [44]:
df_diff = pd.DataFrame()

In [45]:
df_diff['abs_diff'] = df_max - df_min

In [48]:
df_diff['perct'] = (df_max - df_min) / df_min * 100

In [59]:
df_diff

         abs_diff      perct    max    min
ANO MES
2004-05     0.550  29.131356  2.438  1.888
2004-06     0.584  30.543933  2.496  1.912
2004-07     0.609  31.456612  2.545  1.936
2004-08     0.530  26.108374  2.560  2.030
2004-09     0.539  26.538651  2.570  2.031
...           ...        ...    ...    ...
2021-01     1.383  36.109661  5.213  3.830
2021-02     1.688  40.960932  5.809  4.121
2021-03     2.109  46.058091  6.688  4.579
2021-04     1.450  30.353779  6.227  4.777
2021-05     1.391  28.580234  6.258  4.867

[204 rows x 4 columns]

In [50]:
df2.groupby('ANO MES').idxmax()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
ANO MES,,,,,,,,,,,,,,,,,,
2004-05,12118,12118,12088,12083,12064,12141,12064,12104,12077,12104,12077,12131,12098,12107,12120,12078,12140,12087
2004-06,12226,12226,12169,12164,12145,12249,12145,12228,12158,12185,12243,12185,12158,12242,12249,12213,12249,12249
2004-07,12361,12361,12277,12272,12253,12330,12253,12374,12367,12347,12347,12347,12367,12363,12266,12348,12303,12266
2004-08,12469,12469,12412,12407,12388,12438,12388,12471,12428,12471,12401,12428,12395,12483,12404,12483,12439,12438
2004-09,12577,12577,12520,12515,12496,12600,12496,12590,12536,12563,12509,12590,12536,12552,12525,12591,12545,12519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01,118384,118384,117698,117709,117683,118408,117683,118208,118208,118384,118208,117683,118208,117683,117683,117683,117683,117683
2021-02,119092,119092,118575,118586,118560,119116,118560,119092,118750,119092,119092,118560,118750,118560,118560,118560,118560,118560
2021-03,119807,119807,119284,119295,119269,119293,119269,119629,119810,119629,119449,119269,119810,119269,119269,119269,119269,119269
2021-04,120520,120520,120000,120011,119985,120544,119985,120163,120362,119985,120183,119985,119988,119985,119985,119985,119985,119985
2021-05,120699,120699,120714,120725,120699,120723,120699,120699,120703,120699,120699,120699,120703,120699,120699,120699,120699,120699

In [56]:
idx_max = df2.groupby('ANO MES')['PREÇO MÉDIO REVENDA'].idxmax()

In [57]:
idx_min = df2.groupby('ANO MES')['PREÇO MÉDIO REVENDA'].idxmin()

In [58]:
df_diff['max'] = df_max
df_diff['min'] = df_min

In [60]:
df2.loc[idx_max, :][['ESTADO', 'PREÇO MÉDIO REVENDA', 'ANO MES']]

             ESTADO  PREÇO MÉDIO REVENDA  ANO MES
12104          ACRE                2.438  2004-05
12228   MATO GROSSO                2.496  2004-06
12374          ACRE                2.545  2004-07
12471   MATO GROSSO                2.560  2004-08
12590          ACRE                2.570  2004-09
...             ...                  ...      ...
118208         ACRE                5.213  2021-01
119092         ACRE                5.809  2021-02
119629         ACRE                6.688  2021-03
120163         ACRE                6.227  2021-04
120699         ACRE                6.258  2021-05

[204 rows x 3 columns]

In [64]:
df_diff['ESTADO MAX'] = df2.loc[idx_max, :]['ESTADO'].values

In [65]:
df_diff['ESTADO MIN'] = df2.loc[idx_min, :]['ESTADO'].values

In [66]:
df_diff

         abs_diff      perct    max    min   ESTADO MAX        ESTADO MIN
ANO MES
2004-05     0.550  29.131356  2.438  1.888         ACRE         SAO PAULO
2004-06     0.584  30.543933  2.496  1.912  MATO GROSSO         SAO PAULO
2004-07     0.609  31.456612  2.545  1.936         ACRE  DISTRITO FEDERAL
2004-08     0.530  26.108374  2.560  2.030  MATO GROSSO         SAO PAULO
2004-09     0.539  26.538651  2.570  2.031         ACRE         SAO PAULO
...           ...        ...    ...    ...          ...               ...
2021-01     1.383  36.109661  5.213  3.830         ACRE             AMAPA
2021-02     1.688  40.960932  5.809  4.121         ACRE             AMAPA
2021-03     2.109  46.058091  6.688  4.579         ACRE             AMAPA
2021-04     1.450  30.353779  6.227  4.777         ACRE             AMAPA
2021-05     1.391  28.580234  6.258  4.867         ACRE             AMAPA

[204 rows x 6 columns]

In [67]:
df_diff['ESTADO MAX'].value_counts()

ESTADO MAX
ACRE              166
MATO GROSSO        25
RIO DE JANEIRO     11
RORAIMA             2
Name: count, dtype: int64

In [68]:
df_diff['ESTADO MIN'].value_counts()

ESTADO MIN
SAO PAULO              40
AMAPA                  38
PIAUI                  28
PARAIBA                28
PARANA                 14
AMAZONAS               14
DISTRITO FEDERAL       12
MARANHAO                9
SANTA CATARINA          6
PERNAMBUCO              4
MATO GROSSO DO SUL      3
RIO GRANDE DO NORTE     2
GOIAS                   2
BAHIA                   2
CEARA                   2
Name: count, dtype: int64

In [2]:

username = "italofvaz"
os.environ["GITHUB_USER"] = username

!git config --global user.name "${GITHUB_USER}"

In [3]:

usermail = getpass()
os.environ["GITHUB_MAIL"] = usermail

!git config --global user.email "${GITHUB_MAIL}"

··········

In [4]:
usertoken = getpass()
os.environ["GITHUB_TOKEN"] = usertoken

!git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/italofvaz/gas_price_brazil.git

··········
Cloning into 'gas_price_brazil'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 32 (delta 13), reused 20 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (32/32), 6.19 MiB | 14.95 MiB/s, done.
Resolving deltas: 100% (13/13), done.

In [5]:
%cd /content/gas_price_brazil/

/content/gas_price_brazil

In [6]:
!git add .

!git commit -m "test"

!git push origin main

[main 8ed6367] test
 1 file changed, 3366 insertions(+)
 create mode 100644 eda_gas_price_brazil_test.ipynb
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 15.50 KiB | 5.17 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/italofvaz/gas_price_brazil.git
   eb801f1..8ed6367  main -> main